version: '2.2'
services:
  master:
    build:
      context: ./
      dockerfile: master/master.dockerfile
#    depends_on:
#      - node01

  # node01:
  #   build:
  #     context: ./nodes
  #     dockerfile: nodes.dockerfile
  #   volumes:
  #     - ./common:/tmp/common